"""rename address

Revision ID: 533fb9048cea
Revises: 8c24c6a992c1
Create Date: 2024-04-05 13:01:17.474578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533fb9048cea'
down_revision = '8c24c6a992c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
