"""rename department

Revision ID: 8c24c6a992c1
Revises: 8ee6024eabd2
Create Date: 2024-04-05 12:57:44.774160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c24c6a992c1'
down_revision = '8ee6024eabd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
